services:
  router:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - router-data:/app/data
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.middlewares.idleproxy-router-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.idleproxy-router-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.idleproxy-router-http.entrypoints=http"
      - "traefik.http.routers.idleproxy-router-http.middlewares=idleproxy-router-https-redirect"
      - "traefik.http.routers.idleproxy-router-http.priority=100"
      - "traefik.http.routers.idleproxy-router-http.rule=Host(`router.valanamal.xyz`)"
      - "traefik.http.routers.idleproxy-router-http.service=idleproxy-router"
      - "traefik.http.routers.idleproxy-router.entrypoints=https"
      - "traefik.http.routers.idleproxy-router.priority=100"
      - "traefik.http.routers.idleproxy-router.rule=Host(`router.valanamal.xyz`)"
      - "traefik.http.routers.idleproxy-router.service=idleproxy-router"
      - "traefik.http.routers.idleproxy-router.tls=true"
      - "traefik.http.routers.idleproxy-router.tls.certresolver=letsencrypt"
      - "traefik.http.services.idleproxy-router.loadbalancer.server.port=8787"

networks:
  coolify:
    external: true

volumes:
  router-data:
